package com.example.smartwardrobe.enums;

public enum ItemColor {
    MOHOGAMY, WINE, BERRY, RUBY, CRIMSON, RED, ROSE, BLUSH, // RED SHADES
    RUST, BRONZE, FIRE, ORANGE, APRICOT, HONEY, MERIGOLD, CANTALOUPE, // ORANGE SHADES
    GOLDENROD, YELLOW_JASMINE, CITRINE, GOLD, YELLOW, BRIGHT_YELLOW, BUTTER, PALE_YELLOW, // yellow shades
    JUNIPER, CROCODILE, EMERALD, GREEN, PEAR, FERN, SEAFOAM, MINT, // green shades
    DENIM, NAVY, ADMIRAL, BLUE, CERULEAN, TEAL, SKY, ARCTIC, // blue shades
    INDIGO, GRAPE, VIOLET, MARDIGRAS, MAGENTA, ELECTRIC_PURPLE, ORCHID, LAVANDER, //purple shades
    DARK_PINK, BRIGHT_PINK, FUCSIA, WATERMELON, TAFFY, PINK, SALMON, CREPE, //pink shades
    BLACK, GREY, WHITE //non-colors
}